apiVersion: v1
kind: Service
metadata:
  name: flask
  annotations:
    service.beta.kubernetes.io/brightbox-load-balancer-healthcheck-request: /
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: adisakshya/k8s-python-flask
        ports:
          - name: web
            containerPort: 5000
            protocol: TCP