apiVersion: v1
kind: Service
metadata:
  name: flask-microservice
  labels:
    app: flask
    tier: backend
    role: microservice
spec:
  selector:
    app: flask
    tier: backend
    role: microservice
  ports:
    - port: 5000
      targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application
spec:
  selector:
    matchLabels:
      app: flask
      tier: backend
      role: microservice
  replicas: 2
  template:
    metadata:
      labels:
        app: flask
        tier: backend
        role: microservice
    spec:
      containers:
      - name: flask
        image: adisakshya/k8s-python-flask
        ports:
          - containerPort: 5000